USE master
GO

IF EXISTS(SELECT * FROM SYSDATABASES WHERE NAME='QLSV')
DROP DATABASE QLSV
GO

CREATE DATABASE QLSV
GO

USE QLSV
GO


IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME='DEPARTMENT')
DROP TABLE DEPARTMENT
GO

CREATE TABLE DEPARTMENT(
	DID VARCHAR(30) PRIMARY KEY,
	DNAME VARCHAR(30),
	DYEAR INT,
)
GO

IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME='STUDENT')
DROP TABLE STUDENT
GO

CREATE TABLE STUDENT (
	SID VARCHAR(30) PRIMARY KEY,
	NAME NVARCHAR(30) NOT NULL,
	BIRTHDAY VARCHAR(10),
	DID VARCHAR(30),
	FOREIGN KEY (DID) REFERENCES DEPARTMENT(DID),
)

GO

IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME='COURSES')
DROP TABLE COURSES
GO

CREATE TABLE COURSES (
	CID VARCHAR(30) PRIMARY KEY,
	CNAME VARCHAR(30),
	CREDIT INT,
	DID VARCHAR(30),
	FOREIGN KEY (DID) REFERENCES DEPARTMENT(DID),
)

GO

IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME='CONDITION')
DROP TABLE CONDITION
GO

CREATE TABLE CONDITION (
	CID VARCHAR(30),
	PRECID VARCHAR(30),
	PRIMARY KEY (CID ,PRECID),
	FOREIGN KEY (CID) REFERENCES COURSES(CID),
	FOREIGN KEY (PRECID) REFERENCES COURSES(CID),
)

GO

IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME='RESULTS')
DROP TABLE RESULTS
GO

CREATE TABLE RESULTS (
	SID VARCHAR(30),
	CID VARCHAR(30),
	SCORE FLOAT,
	PRIMARY KEY(SID,CID),
	FOREIGN KEY (CID) REFERENCES COURSES(CID),
	FOREIGN KEY (SID) REFERENCES STUDENT(SID),
)
