USE MASTER
GO
IF EXISTS (SELECT * FROM SYSDATABASES WHERE NAME='CSDL')
BEGIN
    DROP DATABASE CSDL
END
GO
CREATE DATABASE CSDL
GO
USE CSDL
GO
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='NSX')
BEGIN
    DROP TABLE NSX
END
GO
CREATE TABLE NSX(
  MaNSX VARCHAR(255) PRIMARY KEY,
  TENNSX NVARCHAR(255) UNIQUE NOT NULL,
)

IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='XEMAY')
BEGIN
    DROP TABLE XEMAY
END
GO
CREATE TABLE XEMAY(
  MAXE VARCHAR(255) PRIMARY KEY,
  TENXE NVARCHAR(255) NOT NULL,
  MANSX VARCHAR(255),
  SOLUONG INT CHECK (SOLUONG > 0),
  DONGIA INT CHECK (DONGIA > 0),
  FOREIGN KEY (MANSX) REFERENCES NSX(MANSX)
)

IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='KHACHHANG')
BEGIN
    DROP TABLE KHACHHANG
END
GO
CREATE TABLE KHACHHANG(
  SDT VARCHAR(11),
  HOTEN NVARCHAR(255) NOT NULL,
  CONSTRAINT KH_SDT_PRI PRIMARY KEY(SDT),
  DIACHI NVARCHAR(20) CHECK(DIACHI IN ('TPHCM', 'Đồng Nai', 'Long An', 'Tây Ninh'))
)
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='HOADON')
BEGIN
    DROP TABLE HOADON
END
GO
CREATE TABLE HOADON(
  SOHOADON INT PRIMARY KEY, 
  NGAYLAP DATE DEFAULT GETDATE(),
  MAKHACHHANG VARCHAR(11),
  CONSTRAINT PK_SDT FOREIGN KEY(MAKHACHHANG) REFERENCES KHACHHANG(SDT)
)
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='CHITIETHOADON')
BEGIN
    DROP TABLE CHITIETHOADON
END
GO
CREATE TABLE CHITIETHOADON(
  SOHOADON INT,
  MAXE VARCHAR(255),
  SOLUONGMUA INT,
  DONGIA INT,
  CONSTRAINT CHECK_SOLUONGMUA CHECK(SOLUONGMUA > 0),
  CONSTRAINT CHECK_DONGIA CHECK(DONGIA > 0),
  CONSTRAINT PRI_CHITIETHOADON PRIMARY KEY (SOHOADON, MAXE),
  CONSTRAINT PK_SOHOADON FOREIGN KEY(SOHOADON) REFERENCES HOADON(SOHOADON),
  CONSTRAINT PK_MAUXE FOREIGN KEY(MAXE) REFERENCES XEMAY(MAXE)
)
-- 2A
ALTER TABLE NSX ADD QUOCGIA NVARCHAR(30)
GO
-- 2B
ALTER TABLE NSX ADD CONSTRAINT CHECK_QUOCGIA CHECK(QUOCGIA IN ('Nhật', 'Hàn', 'Mỹ', 'Đức'))
--2C
ALTER TABLE HOADON ADD NGAYGIAOHANG DATE
GO
--2D
ALTER TABLE HOADON ADD CONSTRAINT CHECK_NGAYGIAOHANG CHECK(NGAYGIAOHANG>=NGAYLAP)
--2E
ALTER TABLE HOADON DROP CONSTRAINT PK_SDT
ALTER TABLE KHACHHANG DROP CONSTRAINT KH_SDT_PRI

ALTER TABLE KHACHHANG ALTER COLUMN SDT INT NOT NULL
ALTER TABLE KHACHHANG ADD PRIMARY KEY(SDT)

ALTER TABLE HOADON ALTER COLUMN MAKHACHHANG INT NOT NULL 
ALTER TABLE HOADON ADD CONSTRAINT PK_SDT FOREIGN KEY(MAKHACHHANG) REFERENCES KHACHHANG(SDT)
--2F
ALTER TABLE HOADON DROP CONSTRAINT PK_SDT
--2G

-- CREATE TABLE CHITIETHOADON(
--   SOHOADON INT,
--   MAXE VARCHAR(255),
--   SOLUONGMUA INT,
--   DONGIA INT,

--   CONSTRAINT CHECK_SOLUONGMUA CHECK(SOLUONGMUA > 0),
--   CONSTRAINT CHECK_DONGIA CHECK(DONGIA > 0),
--   CONSTRAINT PRI_CHITIETHOADON PRIMARY KEY (SOHOADON, MAXE),
--   CONSTRAINT PK_SOHOADON FOREIGN KEY(SOHOADON) REFERENCES HOADON(SOHOADON),
--   CONSTRAINT PK_MAUXE FOREIGN KEY(MAXE) REFERENCES XEMAY(MAXE)
-- )

ALTER TABLE CHITIETHOADON DROP CONSTRAINT CHECK_SOLUONGMUA
ALTER TABLE CHITIETHOADON DROP CONSTRAINT CHECK_DONGIA
ALTER TABLE CHITIETHOADON DROP CONSTRAINT PRI_CHITIETHOADON
ALTER TABLE CHITIETHOADON DROP CONSTRAINT PK_SOHOADON
ALTER TABLE CHITIETHOADON DROP CONSTRAINT PK_MAUXE

