USE MASTER
IF EXISTS (SELECT * FROM SYSDATABASES WHERE NAME = 'DT_NGK')
BEGIN 
  DROP DATABASE DT_NGK
END
CREATE DATABASE DT_NGK
GO
USE DT_NGK 
GO

--A
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'LOAINGK')
BEGIN
  DROP TABLE LOAINGK
END

CREATE TABLE LOAINGK (
  MALOAI VARCHAR(255) PRIMARY KEY, 
  TENLOAI VARCHAR(255) UNIQUE,
)
--B
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'NGK')
BEGIN
  DROP TABLE NGK
END

CREATE TABLE NGK (
  MANGK VARCHAR(255) PRIMARY KEY,
  TENNGK VARCHAR(255) UNIQUE, 
  DVT VARCHAR(10) CHECK (DVT IN ('CHAI','LON','THUNG','KET')),
  SOLUONG INT CHECK(SOLUONG >0),
  DONGIA INT CHECK (DONGIA >0),
  FOREIGN KEY (MANGK) REFERENCES LOAINGK(MALOAI),
)


--C
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'KH')
BEGIN
  DROP TABLE KH
END

CREATE TABLE KH (
  MSKH VARCHAR(255) PRIMARY KEY,
  DIENTHOAI VARCHAR(11) DEFAULT 'CHUA CO'
)


--D
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'HOADON')
BEGIN
  DROP TABLE HOADON
END


CREATE TABLE HOADON (
  SOHOADON VARCHAR(255) PRIMARY KEY, 
  MSKH VARCHAR(255),
  NGAYLAP DATE DEFAULT GETDATE(),
  FOREIGN KEY (MSKH) REFERENCES KH (MSKH)
)

--E
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'CTHD')
BEGIN 
  DROP TABLE CTHD
END

CREATE TABLE CTHD (
  SOHOADON VARCHAR(255),
  MANGK VARCHAR(255),
  SOLUONG INT CHECK(SOLUONG >0),
  PRIMARY KEY (SOHOADON,MANGK)
)

--F
ALTER TABLE CTHD ADD THANHTIEN INT

ALTER TABLE CTHD ADD CONSTRAINT FK_SOHOADON
FOREIGN KEY (SOHOADON) REFERENCES HOADON(SOHOADON)

ALTER TABLE CTHD ADD CONSTRAINT FK_MANGK
FOREIGN KEY (MANGK) REFERENCES NGK(MANGK)


ALTER TABLE CTHD ADD DONGIA INT
GO
ALTER TABLE CTHD ADD CONSTRAINT CHECK_DONGIA CHECK (DONGIA>1000)

--G
ALTER TABLE CTHD DROP CONSTRAINT FK_SOHOADON

--H
ALTER TABLE CTHD ADD CONSTRAINT CHECK_THANHTIEN CHECK (THANHTIEN>0)



