USE MASTER
GO
IF EXISTS (SELECT * FROM SYSDATABASES WHERE NAME = 'DT_NGK')
BEGIN 
  DROP DATABASE DT_NGK
END
GO
CREATE DATABASE DT_NGK
GO
USE DT_NGK 
GO



--1
--A
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'LOAINGK')
BEGIN
  DROP TABLE LOAINGK
END

CREATE TABLE LOAINGK (
  MALOAI VARCHAR(255) PRIMARY KEY, 
  TENLOAI VARCHAR(255) UNIQUE,
)
--B
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'NGK')
BEGIN
  DROP TABLE NGK
END

CREATE TABLE NGK (
  MANGK VARCHAR(255) PRIMARY KEY,
  TENNGK VARCHAR(255) UNIQUE, 
  DVT VARCHAR(10) CHECK (DVT IN ('CHAI','LON','THUNG','KET')),
  SOLUONG INT CHECK(SOLUONG >0),
  DONGIA INT CHECK (DONGIA >0),
  FOREIGN KEY (MANGK) REFERENCES LOAINGK(MALOAI),
)


--C
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'KH')
BEGIN
  DROP TABLE KH
END

CREATE TABLE KH (
  MSKH VARCHAR(255) PRIMARY KEY,
  DIENTHOAI VARCHAR(11) DEFAULT 'CHUA CO'
)


--D
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'HOADON')
BEGIN
  DROP TABLE HOADON
END


CREATE TABLE HOADON (
  SOHOADON VARCHAR(255) PRIMARY KEY, 
  MSKH VARCHAR(255),
  NGAYLAP DATE DEFAULT GETDATE(),
  FOREIGN KEY (MSKH) REFERENCES KH (MSKH)
)

--E
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'CTHD')
BEGIN 
  DROP TABLE CTHD
END

CREATE TABLE CTHD (
  SOHOADON VARCHAR(255),
  MANGK VARCHAR(255),
  SOLUONG INT CHECK(SOLUONG >0),
  PRIMARY KEY (SOHOADON,MANGK)
)

--F
ALTER TABLE CTHD ADD THANHTIEN INT

ALTER TABLE CTHD ADD CONSTRAINT FK_SOHOADON
FOREIGN KEY (SOHOADON) REFERENCES HOADON(SOHOADON)

ALTER TABLE CTHD ADD CONSTRAINT FK_MANGK
FOREIGN KEY (MANGK) REFERENCES NGK(MANGK)


ALTER TABLE CTHD ADD DONGIA INT
GO
ALTER TABLE CTHD ADD CONSTRAINT CHECK_DONGIA CHECK (DONGIA>1000)

--G
ALTER TABLE CTHD DROP CONSTRAINT FK_SOHOADON

--H
ALTER TABLE CTHD ADD CONSTRAINT CHECK_THANHTIEN CHECK (THANHTIEN>0)





--2
--A
INSERT INTO LOAINGK VALUES ('L1','LOAI 1')
INSERT INTO LOAINGK VALUES ('L2','LOAI 2')
INSERT INTO LOAINGK VALUES ('L3','LOAI 3')
SELECT * FROM LOAINGK

INSERT INTO NGK VALUES ('L1','NGK 1','CHAI',10,1000)
INSERT INTO NGK VALUES ('L2','NGK 2','LON',10,2000)
INSERT INTO NGK VALUES ('L3','NGK 3','THUNG',10,3000)
SELECT * FROM NGK

INSERT INTO KH VALUES ('K1','0111111111')
INSERT INTO KH VALUES ('K2','0222222222')
INSERT INTO KH VALUES ('K3','0333333333')
SELECT * FROM KH


SET DATEFORMAT DMY
INSERT INTO HOADON VALUES ('H1','K1','1/1/2022')
INSERT INTO HOADON VALUES ('H2','K2','4/6/2003')
INSERT INTO HOADON VALUES ('H3','K3','9/1/2001')
SELECT * FROM HOADON


INSERT INTO CTHD VALUES ('H1','L1',101,2000,2000)
INSERT INTO CTHD VALUES ('H1','L2',103,3000,1001)
INSERT INTO CTHD VALUES ('H1','L3',104,3000,1002)
INSERT INTO CTHD VALUES ('H2','L1',105,2000,1003)
INSERT INTO CTHD VALUES ('H2','L2',106,2000,1004)
INSERT INTO CTHD VALUES ('H2','L3',107,2000,1005)
SELECT * FROM CTHD

--B
UPDATE NGK SET DONGIA+=10000 WHERE DVT='LON'
--C
DELETE FROM CTHD
WHERE SOHOADON IN (
  SELECT SOHOADON 
  FROM HOADON 
  WHERE YEAR(NGAYLAP) < 2010
)
DELETE FROM HOADON
WHERE YEAR(NGAYLAP) < 2010
DELETE FROM KH
WHERE MSKH NOT IN (
  SELECT MSKH FROM HOADON
)
--D
DELETE NGK
WHERE SOLUONG=0
--E 
UPDATE NGK SET DONGIA=(
  CASE WHEN DONGIA+100000>500000 THEN 500000
  ELSE DONGIA+100000
  END
)
WHERE DVT='THUNG'

--3
--A
SELECT * FROM NGK WHERE DVT='LON'
--B
--C
SELECT DISTINCT TENNGK
FROM NGK, CTHD, HOADON
WHERE NGK.MANGK=CTHD.MANGK
      AND CTHD.SOHOADON=HOADON.SOHOADON
      AND MONTH(HOADON.NGAYLAP) BETWEEN 7 AND 9 
      AND YEAR(HOADON.NGAYLAP)=2018
--D
SELECT TENNGK , SUM(CTHD.SOLUONG) AS 'SO LUONG'
FROM NGK, CTHD, HOADON
WHERE NGK.MANGK=CTHD.MANGK
      AND CTHD.SOHOADON=HOADON.SOHOADON
GROUP BY TENNGK,CTHD.SOLUONG
--E
SELECT DISTINCT SOHOADON
FROM CTHD, NGK
WHERE CTHD.MANGK=NGK.MANGK
      AND NGK.MANGK IN ('L1','L2')

--F
SELECT TENNGK
FROM NGK
WHERE MANGK NOT IN (
  SELECT MANGK
  FROM CTHD
)
















