USE MASTER
IF EXISTS (SELECT * FROM SYSDATABASES WHERE NAME='CSDL' )
DROP DATABASE CSDL
GO
CREATE DATABASE CSDL
GO
USE CSDL
GO
IF EXISTS (SELECT * FROM SYSOBJECTS  WHERE NAME='KETQUA')
DROP TABLE KETQUA;
GO
CREATE TABLE KETQUA (
  -- MASV VARCHAR(255) NOT NULL,
  -- MAMH VARCHAR(255) NOT NULL,
  -- LANTHI INT NOT NULL,
  MASV VARCHAR(255),
  MAMH VARCHAR(255),
  LANTHI INT,
  DIEM FLOAT,
  -- PRIMARY KEY (MASV,MAMH,LANTHI)
)
GO
IF EXISTS (SELECT * FROM SYSOBJECTS  WHERE NAME = 'DMKHOA')
DROP TABLE DMKHOA
GO
CREATE TABLE DMKHOA (
  MAKHOA VARCHAR(255) NOT NULL,
  TENKHOA VARCHAR(255),
  PRIMARY KEY (MAKHOA)
)
GO
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'DMSV')
DROP TABLE DMSV
GO
CREATE TABLE DMSV (
  MASV VARCHAR(255) NOT NULL,
  HOSV VARCHAR(255),
  TENSV VARCHAR(255),
  PHAI VARCHAR(255),
  NGAYSINH DATE,
  NOISINH VARCHAR(255),
  MAKHOA VARCHAR(255),
  HOCBONG VARCHAR(255),
  SOMH INT,
  PRIMARY KEY (MASV)
)
GO
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='DMMH')
DROP TABLE DMMH
GO
CREATE TABLE DMMH(
  MAMH VARCHAR(255) NOT NULL,
  TENMH VARCHAR(255),
  SOTIET INT,
  PRIMARY KEY (MAMH)
)

ALTER TABLE KETQUA ALTER COLUMN MASV VARCHAR(255) NOT NULL
ALTER TABLE KETQUA ALTER COLUMN MAMH VARCHAR(255) NOT NULL
ALTER TABLE KETQUA ALTER COLUMN LANTHI INT NOT NULL
GO
ALTER TABLE KETQUA ADD CONSTRAINT KQ_PK PRIMARY KEY (MASV, MAMH, LANTHI)
ALTER TABLE KETQUA ADD CONSTRAINT KQ_MASV_FK FOREIGN KEY(MASV) REFERENCES DMSV(MASV) 
ALTER TABLE KETQUA ADD CONSTRAINT KQ_MAMH_FK FOREIGN KEY(MAMH) REFERENCES DMMH(MAMH)

--3.1
ALTER TABLE DMKHOA ADD NAMTL INT
--3.2
ALTER TABLE DMKHOA ALTER COLUMN NAMTL SMALLINT
--3.3
EXEC SP_RENAME 'DMKHOA.NAMTL','NAMTHANHLAP' 
--3.4 
ALTER TABLE DMKHOA DROP COLUMN NAMTHANHLAP
--3.6
ALTER TABLE DMSV ADD CONSTRAINT FK_DMSV_KHOA FOREIGN KEY(MAKHOA) REFERENCES DMKHOA(MAKHOA)
--3.5
ALTER TABLE DMSV DROP FK_DMSV_KHOA